### ISSUE TITLE
Percentage is shown as 1.0e+2% when a part is too small

### ISSUE THREAD

**Issue by vladshcherbin** [btd/rollup-plugin-visualizer#26]
Hey,

I see `1.0e+2%` instead of correct percentage. The bundle consists of 2 parts, one is `< 0.1%`, second is `1.0e+2%`.

#### rollup config

```js
/* eslint-disable import/no-extraneous-dependencies */
import replace from 'rollup-plugin-replace'
import resolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'
import visualizer from 'rollup-plugin-visualizer'

export default {
  input: 'src/client/main/index.js',
  output: {
    file: 'build/public/js/main.js',
    format: 'iife'
  },
  plugins: [
    replace({
      'process.env.NODE_ENV': JSON.stringify('production')
    }),
    resolve({
      jsnext: true,
      browser: true
    }),
    commonjs(),
    visualizer()
  ]
}
```

#### input

```js
import React from 'react'
import ReactDOM from 'react-dom'

ReactDOM.render(
  React.createElement('p', null, 'hey'),
  document.getElementById('main')
)
```

#### result

part 1

![rv](https://user-images.githubusercontent.com/6711845/53240115-e4106580-36ae-11e9-8f1a-1a73561b64c5.png)

part 2

![rv](https://user-images.githubusercontent.com/6711845/53240488-e0c9a980-36af-11e9-9e38-bb962cf2e754.png)

#### package versions

rollup - 1.2.2
rollup-plugin-visualizer - 1.0.0
react - 16.8.3
react-dom - 16.8.3

node - 11.7.0
macOS - 10.13.4

I'd expect to see 100%. I can create a repo with issue if needed :)

**Comment by btd** [comment]
Fixed i think

**Comment by vladshcherbin** [comment]
@btd nope, still shows `1.0e+2%`. I can create a repo with issue if needed.

**Comment by btd** [comment]
YEp, could you pls, maybe i did not understand problem correclty

**Comment by vladshcherbin** [comment]
@btd here it is - https://github.com/vladshcherbin/experiments/tree/master/visualizer

**Comment by btd** [comment]
Fixed

**Comment by vladshcherbin** [comment]
@btd yep, fixed. Thanks :)
