### ISSUE TITLE
Deeper view, file names are not shown

### ISSUE THREAD

**Issue by luwes** [btd/rollup-plugin-visualizer#48]
Is it possible to show files deeper in the folder structure?
On my end no `.js` (orange) files are shown in the treemap.
`/static/js` contains many more folders.

<img width="533" alt="Screen Shot 2019-10-31 at 6 34 47 PM" src="https://user-images.githubusercontent.com/360826/67990729-252d2200-fc0d-11e9-8b15-4bf76f99645e.png">

**Comment by btd** [comment]
It is hard to say just from screenshot. Is it possible to share with me stats.html file. It does not contains your source code.

**Comment by luwes** [comment]
Thanks for the reply, I got the folders working by not minifying and running Babel but the files itself are not displayed. Here's the stats.html

https://www.dropbox.com/s/5p0htxr44uu4325/stats.html?dl=0

**Comment by btd** [comment]
Thank you for sharing this was extremely helpful to understand the bug. I caught pretty silly bug. I did not noticed it because i usually use very flat dirs.
Can you pls try fresh version, i think it should be fixed. Maybe will need to adjust some variables.

**Comment by luwes** [comment]
I tried 2.6.1 but it was still the same, update link
https://www.dropbox.com/s/32e0yb63ntgftix/stats.html?dl=0

**Comment by btd** [comment]
i do not see changes for new version in stats file. Are you sure it is 2.6.1?

**Comment by luwes** [comment]
oh snap, I must have had a linked forked version. thanks so much! it works 🎉
