### ISSUE TITLE
Plugins that adds virtual modules and do not follow rollup naming convention breaks reporting

### ISSUE THREAD

**Issue by anncwb** [btd/rollup-plugin-visualizer#93]
Share with me your stats html file. It does not contain your source code - it is completely safe. You can send it to my email (see my github profile).

If you cannot provide me stats html file:

[x] Provide relevant section of your rollup config (at least plugins used).
![image](https://user-images.githubusercontent.com/28132598/113251836-8c18a400-92f5-11eb-9bcd-96e2786644f8.png)

[x] Provide your node and dependencies versions

node: 14.16.1 
dependencies: v5.0.3

[x] Your OS type and version

macos 14.x

[x] Screenshot of problem

If you do not follow template, issue will be closed without comment.

I tried to upgrade to V5 and it doesn't work anymore. V4 can work. My tool is vite2.0

![image](https://user-images.githubusercontent.com/28132598/113232181-37fac900-92cf-11eb-922b-3ce8eb323852.png)

**Comment by btd** [comment]
In case you cannot provide html file i need all information that is in [ ] not just what you selected.

**Comment by btd** [comment]
@anncwb sorry, no. Do you use alias plugin or something that generate/change paths?

**Comment by anncwb** [comment]
There should be. Vite has built-in alias plugin

**Comment by btd** [comment]
Can you please dump me content of variable 'modules' by path ./node_modules/rollup-plugin-visualizer/dist/plugin/data.js on lines 33-34 there is a for cycle. I need modules variable (just `console.log(JSON.stringify(modules))`). I hope it will show what i have not covered. It contains files paths and some size information.

**Comment by anncwb** [comment]
Wait a moment

**Comment by rainmanhhh** [comment]
met exactly the same error

**Comment by btd** [comment]
@rainmanhhh you can do the same as i wrote in comment above

**Comment by anncwb** [comment]
Too much content. . . its stuck

![image](https://user-images.githubusercontent.com/28132598/113255091-021f0a00-92fa-11eb-9369-d0b113d768ab.png)

**Comment by anncwb** [comment]
It seems that there is `undefined`

**Comment by rainmanhhh** [comment]
go back to 4.2.2, everything is ok

**Comment by btd** [comment]
@anncwb fixed, thanks for the help. I just published 5.0.4

**Comment by rainmanhhh** [comment]
> @anncwb fixed, thanks for the help. I just published 5.0.4

no it's not fixed, still report `[visualizer] Error adding node to path`

**Comment by rainmanhhh** [comment]
here is the module cause the error:
```json
  {
    "id": "/@windicss/windi.css",
    "originalLength": 13088,
    "removedExports": [],
    "renderedExports": [
      "default"
    ],
    "renderedLength": 13880,
    "code": "var windi = \"*, ::before, ::after {\\n  -webkit-box-sizing: border-box;\\n  box-sizing: border-box;\\n  border-width: 0;\\n  border-style: solid;\\n  border-color: #e5e7eb;\\n}\\n* {\\n  --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);\\n  --tw-ring-offset-width: 0px;\\n  --tw-ring-offset-color: #fff;\\n  --tw-ring-color: rgba(59, 130, 246, 0.5);\\n  --tw-ring-offset-shadow: 0 0 #0000;\\n  --tw-ring-shadow: 0 0 #0000;\\n  --tw-shadow: 0 0 #0000;\\n}\\n:root {\\n  -moz-tab-size: 4;\\n  -o-tab-size: 4;\\n  tab-size: 4;\\n}\\n:-moz-focusring {\\n  outline: 1px dotted ButtonText;\\n}\\n:-moz-ui-invalid {\\n  box-shadow: none;\\n}\\n::moz-focus-inner {\\n  border-style: none;\\n  padding: 0;\\n}\\n::-webkit-inner-spin-button, ::-webkit-outer-spin-button {\\n  height: auto;\\n}\\n::-webkit-search-decoration {\\n  -webkit-appearance: none;\\n}\\n::-webkit-file-upload-button {\\n  -webkit-appearance: button;\\n  font: inherit;\\n}\\n[type='search'] {\\n  -webkit-appearance: textfield;\\n  outline-offset: -2px;\\n}\\nabbr[title] {\\n  -webkit-text-decoration: underline dotted;\\n  text-decoration: underline dotted;\\n}\\nbody {\\n  margin: 0;\\n  font-family: inherit;\\n  line-height: inherit;\\n}\\nhtml {\\n  -webkit-text-size-adjust: 100%;\\n  font-family: ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,\\\"Segoe UI\\\",Roboto,\\\"Helvetica Neue\\\",Arial,\\\"Noto Sans\\\",sans-serif,\\\"Apple Color Emoji\\\",\\\"Segoe UI Emoji\\\",\\\"Segoe UI Symbol\\\",\\\"Noto Color Emoji\\\";\\n  line-height: 1.5;\\n}\\na {\\n  color: inherit;\\n  text-decoration: inherit;\\n}\\nbutton, input {\\n  font-family: inherit;\\n  font-size: 100%;\\n  line-height: 1.15;\\n  margin: 0;\\n  padding: 0;\\n  line-height: inherit;\\n  color: inherit;\\n}\\nbutton {\\n  text-transform: none;\\n  background-color: transparent;\\n  background-image: none;\\n}\\nbutton, [type='button'], [type='reset'], [type='submit'] {\\n  -webkit-appearance: button;\\n}\\nbutton:focus {\\n  outline: 1px dotted;\\n  outline: 5px auto -webkit-focus-ring-color;\\n}\\nbutton, [role=\\\"button\\\"] {\\n  cursor: pointer;\\n}\\nh3 {\\n  font-size: inherit;\\n  font-weight: inherit;\\n}\\ninput::placeholder {\\n  opacity: 1;\\n  color: #9ca3af;\\n}\\ninput::webkit-input-placeholder {\\n  opacity: 1;\\n  color: #9ca3af;\\n}\\ninput::-moz-placeholder {\\n  opacity: 1;\\n  color: #9ca3af;\\n}\\ninput:-ms-input-placeholder {\\n  opacity: 1;\\n  color: #9ca3af;\\n}\\ninput::-ms-input-placeholder {\\n  opacity: 1;\\n  color: #9ca3af;\\n}\\np, h3 {\\n  margin: 0;\\n}\\n.prose {\\n  color: inherit;\\n  max-width: 65ch;\\n  font-size: 1rem;\\n  line-height: 1.75;\\n}\\n.prose [class~=\\\"lead\\\"] {\\n  color: #4b5563;\\n  font-size: 1.25em;\\n  line-height: 1.6;\\n  margin-top: 1.2em;\\n  margin-bottom: 1.2em;\\n}\\n.prose a {\\n  color: inherit;\\n  text-decoration: underline;\\n  font-weight: 500;\\n}\\n.prose a:hover {\\n  color: #0d9488;\\n}\\n.prose strong {\\n  color: inherit;\\n  font-weight: 600;\\n}\\n.prose ol[type=\\\"A\\\"] {\\n  --list-counter-style: upper-alpha;\\n}\\n.prose ol[type=\\\"a\\\"] {\\n  --list-counter-style: lower-alpha;\\n}\\n.prose ol[type=\\\"A s\\\"] {\\n  --list-counter-style: upper-alpha;\\n}\\n.prose ol[type=\\\"a s\\\"] {\\n  --list-counter-style: lower-alpha;\\n}\\n.prose ol[type=\\\"I\\\"] {\\n  --list-counter-style: upper-roman;\\n}\\n.prose ol[type=\\\"i\\\"] {\\n  --list-counter-style: lower-roman;\\n}\\n.prose ol[type=\\\"I s\\\"] {\\n  --list-counter-style: upper-roman;\\n}\\n.prose ol[type=\\\"i s\\\"] {\\n  --list-counter-style: lower-roman;\\n}\\n.prose ol[type=\\\"1\\\"] {\\n  --list-counter-style: decimal;\\n}\\n.prose ol > li {\\n  position: relative;\\n  padding-left: 1.75em;\\n}\\n.prose ol > li::before {\\n  content: counter(list-item, var(--list-counter-style, decimal)) \\\".\\\";\\n  position: absolute;\\n  font-weight: 400;\\n  color: #6b7280;\\n  left: 0;\\n}\\n.prose ul > li {\\n  position: relative;\\n  padding-left: 1.75em;\\n}\\n.prose ul > li::before {\\n  content: \\\"\\\";\\n  position: absolute;\\n  background-color: #d1d5db;\\n  border-radius: 50%;\\n  width: 0.375em;\\n  height: 0.375em;\\n  top: calc(0.875em - 0.1875em);\\n  left: 0.25em;\\n}\\n.prose hr {\\n  border-color: #e5e7eb;\\n  margin-top: 3em;\\n  margin-bottom: 3em;\\n}\\n.prose blockquote {\\n  font-weight: 500;\\n  font-style: italic;\\n  color: #111827;\\n  border-left-width: 0.25rem;\\n  border-left-color: #e5e7eb;\\n  quotes: \\\"\\\\201C\\\"\\\"\\\\201D\\\"\\\"\\\\2018\\\"\\\"\\\\2019\\\";\\n  margin-top: 1.6em;\\n  margin-bottom: 1.6em;\\n  padding-left: 1em;\\n}\\n.prose blockquote p:first-of-type::before {\\n  content: open-quote;\\n}\\n.prose blockquote p:last-of-type::after {\\n  content: close-quote;\\n}\\n.prose h1 {\\n  color: inherit;\\n  font-weight: 800;\\n  font-size: 2.25em;\\n  margin-top: 0;\\n  margin-bottom: 0.8888889em;\\n  line-height: 1.1111111;\\n}\\n.prose h2 {\\n  color: inherit;\\n  font-weight: 700;\\n  font-size: 1.5em;\\n  margin-top: 2em;\\n  margin-bottom: 1em;\\n  line-height: 1.3333333;\\n}\\n.prose h3 {\\n  color: inherit;\\n  font-weight: 600;\\n  font-size: 1.25em;\\n  margin-top: 1.6em;\\n  margin-bottom: 0.6em;\\n  line-height: 1.6;\\n}\\n.prose h4 {\\n  color: inherit;\\n  font-weight: 600;\\n  margin-top: 1.5em;\\n  margin-bottom: 0.5em;\\n  line-height: 1.5;\\n}\\n.prose figure figcaption {\\n  color: #6b7280;\\n  font-size: 0.875em;\\n  line-height: 1.4285714;\\n  margin-top: 0.8571429em;\\n}\\n.prose code {\\n  color: inherit;\\n  font-weight: 600;\\n  font-size: 0.875em;\\n}\\n.prose code::before {\\n  content: \\\"`\\\";\\n}\\n.prose code::after {\\n  content: \\\"`\\\";\\n}\\n.prose a code {\\n  color: #111827;\\n}\\n.prose pre {\\n  color: #e5e7eb;\\n  background-color: #1f2937;\\n  overflow-x: auto;\\n  font-size: 0.875em;\\n  line-height: 1.7142857;\\n  margin-top: 1.7142857em;\\n  margin-bottom: 1.7142857em;\\n  border-radius: 0.375rem;\\n  padding-top: 0.8571429em;\\n  padding-right: 1.1428571em;\\n  padding-bottom: 0.8571429em;\\n  padding-left: 1.1428571em;\\n}\\n.prose pre code {\\n  background-color: transparent;\\n  border-width: 0;\\n  border-radius: 0;\\n  padding: 0;\\n  font-weight: 400;\\n  color: inherit;\\n  font-size: inherit;\\n  font-family: inherit;\\n  line-height: inherit;\\n}\\n.prose pre code::before {\\n  content: none;\\n}\\n.prose pre code::after {\\n  content: none;\\n}\\n.prose table {\\n  width: 100%;\\n  table-layout: auto;\\n  text-align: left;\\n  margin-top: 2em;\\n  margin-bottom: 2em;\\n  font-size: 0.875em;\\n  line-height: 1.7142857;\\n}\\n.prose thead {\\n  color: #111827;\\n  font-weight: 600;\\n  border-bottom-width: 1px;\\n  border-bottom-color: #d1d5db;\\n}\\n.prose thead th {\\n  vertical-align: bottom;\\n  padding-right: 0.5714286em;\\n  padding-bottom: 0.5714286em;\\n  padding-left: 0.5714286em;\\n}\\n.prose tbody tr {\\n  border-bottom-width: 1px;\\n  border-bottom-color: #e5e7eb;\\n}\\n.prose tbody tr:last-child {\\n  border-bottom-width: 0;\\n}\\n.prose tbody td {\\n  vertical-align: top;\\n  padding-top: 0.5714286em;\\n  padding-right: 0.5714286em;\\n  padding-bottom: 0.5714286em;\\n  padding-left: 0.5714286em;\\n}\\n.prose p {\\n  margin-top: 1.25em;\\n  margin-bottom: 1.25em;\\n}\\n.prose img {\\n  margin-top: 2em;\\n  margin-bottom: 2em;\\n}\\n.prose video {\\n  margin-top: 2em;\\n  margin-bottom: 2em;\\n}\\n.prose figure {\\n  margin-top: 2em;\\n  margin-bottom: 2em;\\n}\\n.prose figure > * {\\n  margin-top: 0;\\n  margin-bottom: 0;\\n}\\n.prose h2 code {\\n  font-size: 0.875em;\\n}\\n.prose h3 code {\\n  font-size: 0.9em;\\n}\\n.prose ol {\\n  margin-top: 1.25em;\\n  margin-bottom: 1.25em;\\n  list-style-type: none;\\n}\\n.prose ul {\\n  margin-top: 1.25em;\\n  margin-bottom: 1.25em;\\n  list-style-type: none;\\n}\\n.prose li {\\n  margin-top: 0.5em;\\n  margin-bottom: 0.5em;\\n}\\n.prose > ul > li p {\\n  margin-top: 0.75em;\\n  margin-bottom: 0.75em;\\n}\\n.prose > ul > li > *:first-child {\\n  margin-top: 1.25em;\\n}\\n.prose > ul > li > *:last-child {\\n  margin-bottom: 1.25em;\\n}\\n.prose > ol > li > *:first-child {\\n  margin-top: 1.25em;\\n}\\n.prose > ol > li > *:last-child {\\n  margin-bottom: 1.25em;\\n}\\n.prose ul ul, .prose ul ol, .prose ol ul, .prose ol ol {\\n  margin-top: 0.75em;\\n  margin-bottom: 0.75em;\\n}\\n.prose hr + * {\\n  margin-top: 0;\\n}\\n.prose h2 + * {\\n  margin-top: 0;\\n}\\n.prose h3 + * {\\n  margin-top: 0;\\n}\\n.prose h4 + * {\\n  margin-top: 0;\\n}\\n.prose thead th:first-child {\\n  padding-left: 0;\\n}\\n.prose thead th:last-child {\\n  padding-right: 0;\\n}\\n.prose tbody td:first-child {\\n  padding-left: 0;\\n}\\n.prose tbody td:last-child {\\n  padding-right: 0;\\n}\\n.prose > :first-child {\\n  margin-top: 0;\\n}\\n.prose > :last-child {\\n  margin-bottom: 0;\\n}\\n.prose b {\\n  color: inherit;\\n}\\n.prose em {\\n  color: inherit;\\n}\\n.prose-sm {\\n  font-size: 0.875rem;\\n  line-height: 1.7142857;\\n}\\n.prose-sm p {\\n  margin-top: 1.1428571em;\\n  margin-bottom: 1.1428571em;\\n}\\n.prose-sm [class~=\\\"lead\\\"] {\\n  font-size: 1.2857143em;\\n  line-height: 1.5555556;\\n  margin-top: 0.8888889em;\\n  margin-bottom: 0.8888889em;\\n}\\n.prose-sm blockquote {\\n  margin-top: 1.3333333em;\\n  margin-bottom: 1.3333333em;\\n  padding-left: 1.1111111em;\\n}\\n.prose-sm h1 {\\n  font-size: 2.1428571em;\\n  margin-top: 0;\\n  margin-bottom: 0.8em;\\n  line-height: 1.2;\\n}\\n.prose-sm h2 {\\n  font-size: 1.4285714em;\\n  margin-top: 1.6em;\\n  margin-bottom: 0.8em;\\n  line-height: 1.4;\\n}\\n.prose-sm h3 {\\n  font-size: 1.2857143em;\\n  margin-top: 1.5555556em;\\n  margin-bottom: 0.4444444em;\\n  line-height: 1.5555556;\\n}\\n.prose-sm h4 {\\n  margin-top: 1.4285714em;\\n  margin-bottom: 0.5714286em;\\n  line-height: 1.4285714;\\n}\\n.prose-sm img {\\n  margin-top: 1.7142857em;\\n  margin-bottom: 1.7142857em;\\n}\\n.prose-sm video {\\n  margin-top: 1.7142857em;\\n  margin-bottom: 1.7142857em;\\n}\\n.prose-sm figure {\\n  margin-top: 1.7142857em;\\n  margin-bottom: 1.7142857em;\\n}\\n.prose-sm figure > * {\\n  margin-top: 0;\\n  margin-bottom: 0;\\n}\\n.prose-sm figure figcaption {\\n  font-size: 0.8571429em;\\n  line-height: 1.3333333;\\n  margin-top: 0.6666667em;\\n}\\n.prose-sm code {\\n  font-size: 0.8571429em;\\n}\\n.prose-sm h2 code {\\n  font-size: 0.9em;\\n}\\n.prose-sm h3 code {\\n  font-size: 0.8888889em;\\n}\\n.prose-sm pre {\\n  font-size: 0.8571429em;\\n  line-height: 1.6666667;\\n  margin-top: 1.6666667em;\\n  margin-bottom: 1.6666667em;\\n  border-radius: 0.25rem;\\n  padding-top: 0.6666667em;\\n  padding-right: 1em;\\n  padding-bottom: 0.6666667em;\\n  padding-left: 1em;\\n}\\n.prose-sm ol {\\n  margin-top: 1.1428571em;\\n  margin-bottom: 1.1428571em;\\n}\\n.prose-sm ul {\\n  margin-top: 1.1428571em;\\n  margin-bottom: 1.1428571em;\\n}\\n.prose-sm li {\\n  margin-top: 0.2857143em;\\n  margin-bottom: 0.2857143em;\\n}\\n.prose-sm ol > li {\\n  padding-left: 1.5714286em;\\n}\\n.prose-sm ol > li::before {\\n  left: 0;\\n}\\n.prose-sm ul > li {\\n  padding-left: 1.5714286em;\\n}\\n.prose-sm ul > li::before {\\n  height: 0.3571429em;\\n  width: 0.3571429em;\\n  top: calc(0.8571429em - 0.1785714em);\\n  left: 0.2142857em;\\n}\\n.prose-sm > ul > li p {\\n  margin-top: 0.5714286em;\\n  margin-bottom: 0.5714286em;\\n}\\n.prose-sm > ul > li > *:first-child {\\n  margin-top: 1.1428571em;\\n}\\n.prose-sm > ul > li > *:last-child {\\n  margin-bottom: 1.1428571em;\\n}\\n.prose-sm > ol > li > *:first-child {\\n  margin-top: 1.1428571em;\\n}\\n.prose-sm > ol > li > *:last-child {\\n  margin-bottom: 1.1428571em;\\n}\\n.prose-sm ul ul, .prose-sm ul ol, .prose-sm ol ul, .prose-sm ol ol {\\n  margin-top: 0.5714286em;\\n  margin-bottom: 0.5714286em;\\n}\\n.prose-sm hr {\\n  margin-top: 2.8571429em;\\n  margin-bottom: 2.8571429em;\\n}\\n.prose-sm hr + * {\\n  margin-top: 0;\\n}\\n.prose-sm h2 + * {\\n  margin-top: 0;\\n}\\n.prose-sm h3 + * {\\n  margin-top: 0;\\n}\\n.prose-sm h4 + * {\\n  margin-top: 0;\\n}\\n.prose-sm table {\\n  font-size: 0.8571429em;\\n  line-height: 1.5;\\n}\\n.prose-sm thead th {\\n  padding-right: 1em;\\n  padding-bottom: 0.6666667em;\\n  padding-left: 1em;\\n}\\n.prose-sm thead th:first-child {\\n  padding-left: 0;\\n}\\n.prose-sm thead th:last-child {\\n  padding-right: 0;\\n}\\n.prose-sm tbody td {\\n  padding-top: 0.6666667em;\\n  padding-right: 1em;\\n  padding-bottom: 0.6666667em;\\n  padding-left: 1em;\\n}\\n.prose-sm tbody td:first-child {\\n  padding-left: 0;\\n}\\n.prose-sm tbody td:last-child {\\n  padding-right: 0;\\n}\\n.prose-sm > :first-child {\\n  margin-top: 0;\\n}\\n.prose-sm > :last-child {\\n  margin-bottom: 0;\\n}\\n.bg-transparent {\\n  background-color: transparent;\\n}\\n.border-gray-200 {\\n  --tw-border-opacity: 1;\\n  border-color: rgba(229, 231, 235, var(--tw-border-opacity));\\n}\\n.dark .dark\\\\:border-gray-700 {\\n  --tw-border-opacity: 1;\\n  border-color: rgba(55, 65, 81, var(--tw-border-opacity));\\n}\\n.rounded {\\n  border-radius: 0.25rem;\\n}\\n.border {\\n  border-width: 1px;\\n}\\n.inline-block {\\n  display: inline-block;\\n}\\n.hidden {\\n  display: none;\\n}\\n.text-xl {\\n  font-size: 1.25rem;\\n  line-height: 1.75rem;\\n}\\n.text-4xl {\\n  font-size: 2.25rem;\\n  line-height: 2.5rem;\\n}\\n.text-sm {\\n  font-size: 0.875rem;\\n  line-height: 1.25rem;\\n}\\n.m-auto {\\n  margin: auto;\\n}\\n.m-3 {\\n  margin: 0.75rem;\\n}\\n.mx-2 {\\n  margin-left: 0.5rem;\\n  margin-right: 0.5rem;\\n}\\n.mx-auto {\\n  margin-left: auto;\\n  margin-right: auto;\\n}\\n.mt-6 {\\n  margin-top: 1.5rem;\\n}\\n.mt-8 {\\n  margin-top: 2rem;\\n}\\n.mt-5 {\\n  margin-top: 1.25rem;\\n}\\n.-mb-6 {\\n  margin-bottom: -1.5rem;\\n}\\n.opacity-25 {\\n  opacity: 0.25;\\n}\\n.opacity-50 {\\n  opacity: 0.5;\\n}\\n.opacity-75 {\\n  opacity: 0.75;\\n}\\n.outline-none {\\n  outline: 2px solid transparent;\\n  outline-offset: 2px;\\n}\\n.active\\\\:outline-none:active {\\n  outline: 2px solid transparent;\\n  outline-offset: 2px;\\n}\\n.py-10 {\\n  padding-top: 2.5rem;\\n  padding-bottom: 2.5rem;\\n}\\n.py-4 {\\n  padding-top: 1rem;\\n  padding-bottom: 1rem;\\n}\\n.py-2 {\\n  padding-top: 0.5rem;\\n  padding-bottom: 0.5rem;\\n}\\n.px-4 {\\n  padding-left: 1rem;\\n  padding-right: 1rem;\\n}\\n.text-left {\\n  text-align: left;\\n}\\n.text-center {\\n  text-align: center;\\n}\\n.text-teal-700 {\\n  --tw-text-opacity: 1;\\n  color: rgba(15, 118, 110, var(--tw-text-opacity));\\n}\\n.text-gray-700 {\\n  --tw-text-opacity: 1;\\n  color: rgba(55, 65, 81, var(--tw-text-opacity));\\n}\\n.dark .dark\\\\:text-gray-200 {\\n  --tw-text-opacity: 1;\\n  color: rgba(229, 231, 235, var(--tw-text-opacity));\\n}\";"
  },
```

**Comment by rainmanhhh** [comment]
plugin/data.js line 41:
```js
        else {
            // id:'/@windicss/windi.css', path_1.default.sep:'\'(why? even on windows the id splitter is '/')
            const pathParts = id.split(path_1.default.sep);
            // pathParts:['/@windicss/windi.css']
            if (path_1.default.isAbsolute(id)) { // true
                pathParts.shift(); // remove '' or C:
                // pathParts after shift: [], '/@windicss/windi.css' was removed because it starts with '/'
            }
            addToPath(tree, pathParts, nodeData);
        }
```

**Comment by rainmanhhh** [comment]
plugin/data.js line 10:
```
const addToPath = (tree, modulePath, node) => {
    if (modulePath.length === 0) {
        throw new Error(`Error adding node to path ${modulePath.join("/")}`); // modulePath.length === 0, join is useless
    }
    const [head, ...rest] = modulePath;
    if (rest.length === 0) {
        tree.children.push({ ...node, name: head });
        return;
    }
    else {
        let newTree = tree.children.find((folder) => folder.name === head && types_1.isModuleTree(folder));
        if (!newTree) {
            newTree = { name: head, children: [] };
            tree.children.push(newTree);
        }
        addToPath(newTree, rest, node);
        return;
    }
};
```
suggest add id to addToPath params so it can report info about which module causes error

**Comment by btd** [comment]
@rainmanhhh thanks for detailed report, what you are is another issue not related to what originally was reported.
Can you explain what is adding /@windicss/windi.css for you?

**Comment by btd** [comment]
It is again some weird plugin that do not follow naming convention https://github.com/windicss/vite-plugin-windicss/blob/main/packages/rollup-plugin-windicss/src/index.ts#L7

I will fix it more generic way later today or tomorrow.

**Comment by btd** [comment]
@rainmanhhh i think i fixed your use case also. Try 5.1.0
